import SearchHeader from '@/components/SearchHeader'
export const metadata = {
  title: 'Searching...',
  description: 'Generated by create next app',
}

export default function SearchLayout({ children }) {
  return (
    <div>
      <SearchHeader/>
      {children}
    </div>
  )
}
